/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Topic = {
  _id: string;
  _type: "topic";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  showArticleEyebrow?: boolean;
  parent?: CategoryReference;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  role: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type TopicReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "topic";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  categories: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  topics?: Array<
    {
      _key: string;
    } & TopicReference
  >;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        credit?: string;
        _type: "image";
        _key: string;
      }
  >;
  summary?: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    credit?: string;
    _type: "image";
  };
  date?: string;
  authors?: Array<
    {
      _key: string;
    } & AuthorReference
  >;
};

export type ArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "article";
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  about?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  featuredArticles?: Array<
    {
      _key: string;
    } & ArticleReference
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Topic
  | Slug
  | CategoryReference
  | Category
  | SanityImageAssetReference
  | Author
  | SanityImageCrop
  | SanityImageHotspot
  | TopicReference
  | AuthorReference
  | Article
  | ArticleReference
  | Settings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/fetch.ts
// Variable: articleQuery
// Query: *[_type == "article" && slug.current == $slug] [0] {			content[] {				...,				_type == "image" => {					"url": @.asset->url,					"aspectRatio": @.asset->metadata.dimensions.aspectRatio,					"lqip": @.asset->metadata.lqip,					alt,					caption,				}			},			"dateModified": _updatedAt,			// groq  _id,  "title": coalesce(title, "Untitled"),  "slug": slug.current,  summary,  "primaryCategory": categories[0]-> {    _id,    "title": coalesce(title, "Untitled Category"),    "slug": slug.current,    "showArticleEyebrow": coalesce(showArticleEyebrow, false),  },  categories[] -> {    _id,    "title": coalesce(title, "Untitled Category"),    "slug": slug.current,    "showArticleEyebrow": coalesce(showArticleEyebrow, false),  },  "date": coalesce(date, _updatedAt),  "url": coalesce("/" + categories[0]->slug.current + "/" + slug.current, "/"),  authors[] -> {    "name": coalesce(name, "Unknown Author"),    "slug": slug.current,  },  "topics": array::compact(    coalesce(      topics[]-> {        "name": coalesce(name, "Untitled Topic"),        "slug": slug.current,      },      []    )  ),  "coverImage": {	"url": coverImage.asset->url,	"aspectRatio": coverImage.asset->metadata.dimensions.aspectRatio,	"lqip": coverImage.asset->metadata.lqip,	"alt": coverImage.alt,	"caption": coverImage.caption,	"credit": coverImage.credit,  }		}
export type ArticleQueryResult = {
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string | null;
        caption: string | null;
        credit?: string;
        _type: "image";
        _key: string;
        url: string | null;
        aspectRatio: number | null;
        lqip: string | null;
      }
  > | null;
  dateModified: string;
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  primaryCategory: {
    _id: string;
    title: string;
    slug: string;
    showArticleEyebrow: boolean | false;
  } | null;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
    showArticleEyebrow: boolean | false;
  }>;
  date: string;
  url: string | "/";
  authors: Array<{
    name: string;
    slug: string;
  }> | null;
  topics:
    | Array<{
        name: string;
        slug: string;
      }>
    | Array<never>;
  coverImage: {
    url: string | null;
    aspectRatio: number | null;
    lqip: string | null;
    alt: string | null;
    caption: string | null;
    credit: string | null;
  };
} | null;

// Source: ../web/src/sanity/fetch.ts
// Variable: latestArticlesQuery
// Query: *[_type == "article"] | order(date desc) [0...20] {			// groq  _id,  "title": coalesce(title, "Untitled"),  "slug": slug.current,  summary,  "primaryCategory": categories[0]-> {    _id,    "title": coalesce(title, "Untitled Category"),    "slug": slug.current,    "showArticleEyebrow": coalesce(showArticleEyebrow, false),  },  categories[] -> {    _id,    "title": coalesce(title, "Untitled Category"),    "slug": slug.current,    "showArticleEyebrow": coalesce(showArticleEyebrow, false),  },  "date": coalesce(date, _updatedAt),  "url": coalesce("/" + categories[0]->slug.current + "/" + slug.current, "/"),  authors[] -> {    "name": coalesce(name, "Unknown Author"),    "slug": slug.current,  },  "topics": array::compact(    coalesce(      topics[]-> {        "name": coalesce(name, "Untitled Topic"),        "slug": slug.current,      },      []    )  ),  "coverImage": {	"url": coverImage.asset->url,	"aspectRatio": coverImage.asset->metadata.dimensions.aspectRatio,	"lqip": coverImage.asset->metadata.lqip,	"alt": coverImage.alt,	"caption": coverImage.caption,	"credit": coverImage.credit,  }		}
export type LatestArticlesQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  primaryCategory: {
    _id: string;
    title: string;
    slug: string;
    showArticleEyebrow: boolean | false;
  } | null;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
    showArticleEyebrow: boolean | false;
  }>;
  date: string;
  url: string | "/";
  authors: Array<{
    name: string;
    slug: string;
  }> | null;
  topics:
    | Array<{
        name: string;
        slug: string;
      }>
    | Array<never>;
  coverImage: {
    url: string | null;
    aspectRatio: number | null;
    lqip: string | null;
    alt: string | null;
    caption: string | null;
    credit: string | null;
  };
}>;

// Source: ../web/src/sanity/fetch.ts
// Variable: categoryQuery
// Query: *[_type == "category" && slug.current == $slug] [0] {      _id,      "title": coalesce(title, "Untitled Category"),      "slug": slug.current,      description    }
export type CategoryQueryResult = {
  _id: string;
  title: string;
  slug: string;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: ../web/src/sanity/fetch.ts
// Variable: articlesByCategoryQuery
// Query: *[      _type == "article" &&      $slug in categories[]->slug.current    ] | order(date desc) [0...14] {      // groq  _id,  "title": coalesce(title, "Untitled"),  "slug": slug.current,  summary,  "primaryCategory": categories[0]-> {    _id,    "title": coalesce(title, "Untitled Category"),    "slug": slug.current,    "showArticleEyebrow": coalesce(showArticleEyebrow, false),  },  categories[] -> {    _id,    "title": coalesce(title, "Untitled Category"),    "slug": slug.current,    "showArticleEyebrow": coalesce(showArticleEyebrow, false),  },  "date": coalesce(date, _updatedAt),  "url": coalesce("/" + categories[0]->slug.current + "/" + slug.current, "/"),  authors[] -> {    "name": coalesce(name, "Unknown Author"),    "slug": slug.current,  },  "topics": array::compact(    coalesce(      topics[]-> {        "name": coalesce(name, "Untitled Topic"),        "slug": slug.current,      },      []    )  ),  "coverImage": {	"url": coverImage.asset->url,	"aspectRatio": coverImage.asset->metadata.dimensions.aspectRatio,	"lqip": coverImage.asset->metadata.lqip,	"alt": coverImage.alt,	"caption": coverImage.caption,	"credit": coverImage.credit,  }    }
export type ArticlesByCategoryQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  primaryCategory: {
    _id: string;
    title: string;
    slug: string;
    showArticleEyebrow: boolean | false;
  } | null;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
    showArticleEyebrow: boolean | false;
  }>;
  date: string;
  url: string | "/";
  authors: Array<{
    name: string;
    slug: string;
  }> | null;
  topics:
    | Array<{
        name: string;
        slug: string;
      }>
    | Array<never>;
  coverImage: {
    url: string | null;
    aspectRatio: number | null;
    lqip: string | null;
    alt: string | null;
    caption: string | null;
    credit: string | null;
  };
}>;

// Source: ../web/src/sanity/fetch.ts
// Variable: allCategoriesQuery
// Query: *[_type == "category"] | order(title asc) {      _id,      "title": coalesce(title, "Untitled Category"),      "slug": slug.current,    }
export type AllCategoriesQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
}>;

// Source: ../web/src/sanity/fetch.ts
// Variable: topicQuery
// Query: *[_type == "topic" && slug.current == $slug] [0] {      _id,      "name": coalesce(name, "Untitled Topic"),      "slug": slug.current,      description    }
export type TopicQueryResult = {
  _id: string;
  name: string;
  slug: string;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: ../web/src/sanity/fetch.ts
// Variable: articlesByTopicQuery
// Query: *[      _type == "article" &&      $slug in topics[]->slug.current    ] | order(date desc) [0...14] {      // groq  _id,  "title": coalesce(title, "Untitled"),  "slug": slug.current,  summary,  "primaryCategory": categories[0]-> {    _id,    "title": coalesce(title, "Untitled Category"),    "slug": slug.current,    "showArticleEyebrow": coalesce(showArticleEyebrow, false),  },  categories[] -> {    _id,    "title": coalesce(title, "Untitled Category"),    "slug": slug.current,    "showArticleEyebrow": coalesce(showArticleEyebrow, false),  },  "date": coalesce(date, _updatedAt),  "url": coalesce("/" + categories[0]->slug.current + "/" + slug.current, "/"),  authors[] -> {    "name": coalesce(name, "Unknown Author"),    "slug": slug.current,  },  "topics": array::compact(    coalesce(      topics[]-> {        "name": coalesce(name, "Untitled Topic"),        "slug": slug.current,      },      []    )  ),  "coverImage": {	"url": coverImage.asset->url,	"aspectRatio": coverImage.asset->metadata.dimensions.aspectRatio,	"lqip": coverImage.asset->metadata.lqip,	"alt": coverImage.alt,	"caption": coverImage.caption,	"credit": coverImage.credit,  }    }
export type ArticlesByTopicQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  primaryCategory: {
    _id: string;
    title: string;
    slug: string;
    showArticleEyebrow: boolean | false;
  } | null;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
    showArticleEyebrow: boolean | false;
  }>;
  date: string;
  url: string | "/";
  authors: Array<{
    name: string;
    slug: string;
  }> | null;
  topics:
    | Array<{
        name: string;
        slug: string;
      }>
    | Array<never>;
  coverImage: {
    url: string | null;
    aspectRatio: number | null;
    lqip: string | null;
    alt: string | null;
    caption: string | null;
    credit: string | null;
  };
}>;

// Source: ../web/src/sanity/fetch.ts
// Variable: allTopicsQuery
// Query: *[_type == "topic"] | order(name asc) {      _id,      "name": coalesce(name, "Untitled Topic"),      "slug": slug.current,    }
export type AllTopicsQueryResult = Array<{
  _id: string;
  name: string;
  slug: string;
}>;

// Source: ../web/src/sanity/fetch.ts
// Variable: allArticlesQuery
// Query: *[_type == "article"] | order(date desc) {			// groq  _id,  "title": coalesce(title, "Untitled"),  "slug": slug.current,  summary,  "primaryCategory": categories[0]-> {    _id,    "title": coalesce(title, "Untitled Category"),    "slug": slug.current,    "showArticleEyebrow": coalesce(showArticleEyebrow, false),  },  categories[] -> {    _id,    "title": coalesce(title, "Untitled Category"),    "slug": slug.current,    "showArticleEyebrow": coalesce(showArticleEyebrow, false),  },  "date": coalesce(date, _updatedAt),  "url": coalesce("/" + categories[0]->slug.current + "/" + slug.current, "/"),  authors[] -> {    "name": coalesce(name, "Unknown Author"),    "slug": slug.current,  },  "topics": array::compact(    coalesce(      topics[]-> {        "name": coalesce(name, "Untitled Topic"),        "slug": slug.current,      },      []    )  ),  "coverImage": {	"url": coverImage.asset->url,	"aspectRatio": coverImage.asset->metadata.dimensions.aspectRatio,	"lqip": coverImage.asset->metadata.lqip,	"alt": coverImage.alt,	"caption": coverImage.caption,	"credit": coverImage.credit,  }		}
export type AllArticlesQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  primaryCategory: {
    _id: string;
    title: string;
    slug: string;
    showArticleEyebrow: boolean | false;
  } | null;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
    showArticleEyebrow: boolean | false;
  }>;
  date: string;
  url: string | "/";
  authors: Array<{
    name: string;
    slug: string;
  }> | null;
  topics:
    | Array<{
        name: string;
        slug: string;
      }>
    | Array<never>;
  coverImage: {
    url: string | null;
    aspectRatio: number | null;
    lqip: string | null;
    alt: string | null;
    caption: string | null;
    credit: string | null;
  };
}>;

// Source: ../web/src/sanity/fetch.ts
// Variable: settingsQuery
// Query: *[_type == "settings"] [0] {			about		}
export type SettingsQueryResult = {
  about: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: ../web/src/sanity/fetch.ts
// Variable: featuredArticlesQuery
// Query: coalesce(      *[_type == "settings"][0].featuredArticles[]-> {        // groq  _id,  "title": coalesce(title, "Untitled"),  "slug": slug.current,  summary,  "primaryCategory": categories[0]-> {    _id,    "title": coalesce(title, "Untitled Category"),    "slug": slug.current,    "showArticleEyebrow": coalesce(showArticleEyebrow, false),  },  categories[] -> {    _id,    "title": coalesce(title, "Untitled Category"),    "slug": slug.current,    "showArticleEyebrow": coalesce(showArticleEyebrow, false),  },  "date": coalesce(date, _updatedAt),  "url": coalesce("/" + categories[0]->slug.current + "/" + slug.current, "/"),  authors[] -> {    "name": coalesce(name, "Unknown Author"),    "slug": slug.current,  },  "topics": array::compact(    coalesce(      topics[]-> {        "name": coalesce(name, "Untitled Topic"),        "slug": slug.current,      },      []    )  ),  "coverImage": {	"url": coverImage.asset->url,	"aspectRatio": coverImage.asset->metadata.dimensions.aspectRatio,	"lqip": coverImage.asset->metadata.lqip,	"alt": coverImage.alt,	"caption": coverImage.caption,	"credit": coverImage.credit,  }      },      []    )
export type FeaturedArticlesQueryResult =
  | Array<{
      _id: string;
      title: string;
      slug: string;
      summary: string | null;
      primaryCategory: {
        _id: string;
        title: string;
        slug: string;
        showArticleEyebrow: boolean | false;
      } | null;
      categories: Array<{
        _id: string;
        title: string;
        slug: string;
        showArticleEyebrow: boolean | false;
      }>;
      date: string;
      url: string | "/";
      authors: Array<{
        name: string;
        slug: string;
      }> | null;
      topics:
        | Array<{
            name: string;
            slug: string;
          }>
        | Array<never>;
      coverImage: {
        url: string | null;
        aspectRatio: number | null;
        lqip: string | null;
        alt: string | null;
        caption: string | null;
        credit: string | null;
      };
    }>
  | Array<never>;

// Source: ../web/src/sanity/fetch.ts
// Variable: authorQuery
// Query: *[_type == "author" && slug.current == $slug] [0] {			...,			"photo": {				"url": photo.asset->url,				"aspectRatio": photo.asset->metadata.dimensions.aspectRatio,				"lqip": photo.asset->metadata.lqip,			}		}
export type AuthorQueryResult = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  role: string;
  photo: {
    url: string | null;
    aspectRatio: number | null;
    lqip: string | null;
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
} | null;

// Source: ../web/src/sanity/fetch.ts
// Variable: articlesByAuthorQuery
// Query: *[      _type == "article" &&      $slug in authors[]->slug.current    ] | order(date desc) {      // groq  _id,  "title": coalesce(title, "Untitled"),  "slug": slug.current,  summary,  "primaryCategory": categories[0]-> {    _id,    "title": coalesce(title, "Untitled Category"),    "slug": slug.current,    "showArticleEyebrow": coalesce(showArticleEyebrow, false),  },  categories[] -> {    _id,    "title": coalesce(title, "Untitled Category"),    "slug": slug.current,    "showArticleEyebrow": coalesce(showArticleEyebrow, false),  },  "date": coalesce(date, _updatedAt),  "url": coalesce("/" + categories[0]->slug.current + "/" + slug.current, "/"),  authors[] -> {    "name": coalesce(name, "Unknown Author"),    "slug": slug.current,  },  "topics": array::compact(    coalesce(      topics[]-> {        "name": coalesce(name, "Untitled Topic"),        "slug": slug.current,      },      []    )  ),  "coverImage": {	"url": coverImage.asset->url,	"aspectRatio": coverImage.asset->metadata.dimensions.aspectRatio,	"lqip": coverImage.asset->metadata.lqip,	"alt": coverImage.alt,	"caption": coverImage.caption,	"credit": coverImage.credit,  }    }
export type ArticlesByAuthorQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  primaryCategory: {
    _id: string;
    title: string;
    slug: string;
    showArticleEyebrow: boolean | false;
  } | null;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
    showArticleEyebrow: boolean | false;
  }>;
  date: string;
  url: string | "/";
  authors: Array<{
    name: string;
    slug: string;
  }> | null;
  topics:
    | Array<{
        name: string;
        slug: string;
      }>
    | Array<never>;
  coverImage: {
    url: string | null;
    aspectRatio: number | null;
    lqip: string | null;
    alt: string | null;
    caption: string | null;
    credit: string | null;
  };
}>;

// Source: ../web/src/sanity/fetch.ts
// Variable: allAuthorsQuery
// Query: *[_type == "author"] {			slug,			role,			name,		}
export type AllAuthorsQueryResult = Array<{
  slug: Slug;
  role: string;
  name: string;
}>;

// Source: ../web/src/sanity/rewrites.ts
// Variable: categorySlugsQuery
// Query: *[_type == "category"].slug.current
export type CategorySlugsQueryResult = Array<string>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n\t\t*[_type == "article" && slug.current == $slug] [0] {\n\t\t\tcontent[] {\n\t\t\t\t...,\n\t\t\t\t_type == "image" => {\n\t\t\t\t\t"url": @.asset->url,\n\t\t\t\t\t"aspectRatio": @.asset->metadata.dimensions.aspectRatio,\n\t\t\t\t\t"lqip": @.asset->metadata.lqip,\n\t\t\t\t\talt,\n\t\t\t\t\tcaption,\n\t\t\t\t}\n\t\t\t},\n\t\t\t"dateModified": _updatedAt,\n\t\t\t// groq\n  _id,\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  summary,\n  "primaryCategory": categories[0]-> {\n    _id,\n    "title": coalesce(title, "Untitled Category"),\n    "slug": slug.current,\n    "showArticleEyebrow": coalesce(showArticleEyebrow, false),\n  },\n  categories[] -> {\n    _id,\n    "title": coalesce(title, "Untitled Category"),\n    "slug": slug.current,\n    "showArticleEyebrow": coalesce(showArticleEyebrow, false),\n  },\n  "date": coalesce(date, _updatedAt),\n  "url": coalesce("/" + categories[0]->slug.current + "/" + slug.current, "/"),\n  authors[] -> {\n    "name": coalesce(name, "Unknown Author"),\n    "slug": slug.current,\n  },\n  "topics": array::compact(\n    coalesce(\n      topics[]-> {\n        "name": coalesce(name, "Untitled Topic"),\n        "slug": slug.current,\n      },\n      []\n    )\n  ),\n  "coverImage": {\n\t"url": coverImage.asset->url,\n\t"aspectRatio": coverImage.asset->metadata.dimensions.aspectRatio,\n\t"lqip": coverImage.asset->metadata.lqip,\n\t"alt": coverImage.alt,\n\t"caption": coverImage.caption,\n\t"credit": coverImage.credit,\n  }\n\n\t\t}\n\t': ArticleQueryResult;
    '\n\t\t*[_type == "article"] | order(date desc) [0...20] {\n\t\t\t// groq\n  _id,\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  summary,\n  "primaryCategory": categories[0]-> {\n    _id,\n    "title": coalesce(title, "Untitled Category"),\n    "slug": slug.current,\n    "showArticleEyebrow": coalesce(showArticleEyebrow, false),\n  },\n  categories[] -> {\n    _id,\n    "title": coalesce(title, "Untitled Category"),\n    "slug": slug.current,\n    "showArticleEyebrow": coalesce(showArticleEyebrow, false),\n  },\n  "date": coalesce(date, _updatedAt),\n  "url": coalesce("/" + categories[0]->slug.current + "/" + slug.current, "/"),\n  authors[] -> {\n    "name": coalesce(name, "Unknown Author"),\n    "slug": slug.current,\n  },\n  "topics": array::compact(\n    coalesce(\n      topics[]-> {\n        "name": coalesce(name, "Untitled Topic"),\n        "slug": slug.current,\n      },\n      []\n    )\n  ),\n  "coverImage": {\n\t"url": coverImage.asset->url,\n\t"aspectRatio": coverImage.asset->metadata.dimensions.aspectRatio,\n\t"lqip": coverImage.asset->metadata.lqip,\n\t"alt": coverImage.alt,\n\t"caption": coverImage.caption,\n\t"credit": coverImage.credit,\n  }\n\n\t\t}\n\t': LatestArticlesQueryResult;
    '\n\t\t*[_type == "category" && slug.current == $slug] [0] {\n      _id,\n      "title": coalesce(title, "Untitled Category"),\n      "slug": slug.current,\n      description\n    }\n\t': CategoryQueryResult;
    '\n    *[\n      _type == "article" &&\n      $slug in categories[]->slug.current\n    ] | order(date desc) [0...14] {\n      // groq\n  _id,\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  summary,\n  "primaryCategory": categories[0]-> {\n    _id,\n    "title": coalesce(title, "Untitled Category"),\n    "slug": slug.current,\n    "showArticleEyebrow": coalesce(showArticleEyebrow, false),\n  },\n  categories[] -> {\n    _id,\n    "title": coalesce(title, "Untitled Category"),\n    "slug": slug.current,\n    "showArticleEyebrow": coalesce(showArticleEyebrow, false),\n  },\n  "date": coalesce(date, _updatedAt),\n  "url": coalesce("/" + categories[0]->slug.current + "/" + slug.current, "/"),\n  authors[] -> {\n    "name": coalesce(name, "Unknown Author"),\n    "slug": slug.current,\n  },\n  "topics": array::compact(\n    coalesce(\n      topics[]-> {\n        "name": coalesce(name, "Untitled Topic"),\n        "slug": slug.current,\n      },\n      []\n    )\n  ),\n  "coverImage": {\n\t"url": coverImage.asset->url,\n\t"aspectRatio": coverImage.asset->metadata.dimensions.aspectRatio,\n\t"lqip": coverImage.asset->metadata.lqip,\n\t"alt": coverImage.alt,\n\t"caption": coverImage.caption,\n\t"credit": coverImage.credit,\n  }\n\n    }\n  ': ArticlesByCategoryQueryResult;
    '\n    *[_type == "category"] | order(title asc) {\n      _id,\n      "title": coalesce(title, "Untitled Category"),\n      "slug": slug.current,\n    }\n  ': AllCategoriesQueryResult;
    '\n    *[_type == "topic" && slug.current == $slug] [0] {\n      _id,\n      "name": coalesce(name, "Untitled Topic"),\n      "slug": slug.current,\n      description\n    }\n  ': TopicQueryResult;
    '\n    *[\n      _type == "article" &&\n      $slug in topics[]->slug.current\n    ] | order(date desc) [0...14] {\n      // groq\n  _id,\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  summary,\n  "primaryCategory": categories[0]-> {\n    _id,\n    "title": coalesce(title, "Untitled Category"),\n    "slug": slug.current,\n    "showArticleEyebrow": coalesce(showArticleEyebrow, false),\n  },\n  categories[] -> {\n    _id,\n    "title": coalesce(title, "Untitled Category"),\n    "slug": slug.current,\n    "showArticleEyebrow": coalesce(showArticleEyebrow, false),\n  },\n  "date": coalesce(date, _updatedAt),\n  "url": coalesce("/" + categories[0]->slug.current + "/" + slug.current, "/"),\n  authors[] -> {\n    "name": coalesce(name, "Unknown Author"),\n    "slug": slug.current,\n  },\n  "topics": array::compact(\n    coalesce(\n      topics[]-> {\n        "name": coalesce(name, "Untitled Topic"),\n        "slug": slug.current,\n      },\n      []\n    )\n  ),\n  "coverImage": {\n\t"url": coverImage.asset->url,\n\t"aspectRatio": coverImage.asset->metadata.dimensions.aspectRatio,\n\t"lqip": coverImage.asset->metadata.lqip,\n\t"alt": coverImage.alt,\n\t"caption": coverImage.caption,\n\t"credit": coverImage.credit,\n  }\n\n    }\n  ': ArticlesByTopicQueryResult;
    '\n    *[_type == "topic"] | order(name asc) {\n      _id,\n      "name": coalesce(name, "Untitled Topic"),\n      "slug": slug.current,\n    }\n  ': AllTopicsQueryResult;
    '\n\t\t*[_type == "article"] | order(date desc) {\n\t\t\t// groq\n  _id,\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  summary,\n  "primaryCategory": categories[0]-> {\n    _id,\n    "title": coalesce(title, "Untitled Category"),\n    "slug": slug.current,\n    "showArticleEyebrow": coalesce(showArticleEyebrow, false),\n  },\n  categories[] -> {\n    _id,\n    "title": coalesce(title, "Untitled Category"),\n    "slug": slug.current,\n    "showArticleEyebrow": coalesce(showArticleEyebrow, false),\n  },\n  "date": coalesce(date, _updatedAt),\n  "url": coalesce("/" + categories[0]->slug.current + "/" + slug.current, "/"),\n  authors[] -> {\n    "name": coalesce(name, "Unknown Author"),\n    "slug": slug.current,\n  },\n  "topics": array::compact(\n    coalesce(\n      topics[]-> {\n        "name": coalesce(name, "Untitled Topic"),\n        "slug": slug.current,\n      },\n      []\n    )\n  ),\n  "coverImage": {\n\t"url": coverImage.asset->url,\n\t"aspectRatio": coverImage.asset->metadata.dimensions.aspectRatio,\n\t"lqip": coverImage.asset->metadata.lqip,\n\t"alt": coverImage.alt,\n\t"caption": coverImage.caption,\n\t"credit": coverImage.credit,\n  }\n\n\t\t}\n\t': AllArticlesQueryResult;
    '\n\t\t*[_type == "settings"] [0] {\n\t\t\tabout\n\t\t}\n\t': SettingsQueryResult;
    '\n    coalesce(\n      *[_type == "settings"][0].featuredArticles[]-> {\n        // groq\n  _id,\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  summary,\n  "primaryCategory": categories[0]-> {\n    _id,\n    "title": coalesce(title, "Untitled Category"),\n    "slug": slug.current,\n    "showArticleEyebrow": coalesce(showArticleEyebrow, false),\n  },\n  categories[] -> {\n    _id,\n    "title": coalesce(title, "Untitled Category"),\n    "slug": slug.current,\n    "showArticleEyebrow": coalesce(showArticleEyebrow, false),\n  },\n  "date": coalesce(date, _updatedAt),\n  "url": coalesce("/" + categories[0]->slug.current + "/" + slug.current, "/"),\n  authors[] -> {\n    "name": coalesce(name, "Unknown Author"),\n    "slug": slug.current,\n  },\n  "topics": array::compact(\n    coalesce(\n      topics[]-> {\n        "name": coalesce(name, "Untitled Topic"),\n        "slug": slug.current,\n      },\n      []\n    )\n  ),\n  "coverImage": {\n\t"url": coverImage.asset->url,\n\t"aspectRatio": coverImage.asset->metadata.dimensions.aspectRatio,\n\t"lqip": coverImage.asset->metadata.lqip,\n\t"alt": coverImage.alt,\n\t"caption": coverImage.caption,\n\t"credit": coverImage.credit,\n  }\n\n      },\n      []\n    )\n  ': FeaturedArticlesQueryResult;
    '\n\t\t*[_type == "author" && slug.current == $slug] [0] {\n\t\t\t...,\n\t\t\t"photo": {\n\t\t\t\t"url": photo.asset->url,\n\t\t\t\t"aspectRatio": photo.asset->metadata.dimensions.aspectRatio,\n\t\t\t\t"lqip": photo.asset->metadata.lqip,\n\t\t\t}\n\t\t}\n\t': AuthorQueryResult;
    '\n    *[\n      _type == "article" &&\n      $slug in authors[]->slug.current\n    ] | order(date desc) {\n      // groq\n  _id,\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  summary,\n  "primaryCategory": categories[0]-> {\n    _id,\n    "title": coalesce(title, "Untitled Category"),\n    "slug": slug.current,\n    "showArticleEyebrow": coalesce(showArticleEyebrow, false),\n  },\n  categories[] -> {\n    _id,\n    "title": coalesce(title, "Untitled Category"),\n    "slug": slug.current,\n    "showArticleEyebrow": coalesce(showArticleEyebrow, false),\n  },\n  "date": coalesce(date, _updatedAt),\n  "url": coalesce("/" + categories[0]->slug.current + "/" + slug.current, "/"),\n  authors[] -> {\n    "name": coalesce(name, "Unknown Author"),\n    "slug": slug.current,\n  },\n  "topics": array::compact(\n    coalesce(\n      topics[]-> {\n        "name": coalesce(name, "Untitled Topic"),\n        "slug": slug.current,\n      },\n      []\n    )\n  ),\n  "coverImage": {\n\t"url": coverImage.asset->url,\n\t"aspectRatio": coverImage.asset->metadata.dimensions.aspectRatio,\n\t"lqip": coverImage.asset->metadata.lqip,\n\t"alt": coverImage.alt,\n\t"caption": coverImage.caption,\n\t"credit": coverImage.credit,\n  }\n\n    }\n  ': ArticlesByAuthorQueryResult;
    '\n\t\t*[_type == "author"] {\n\t\t\tslug,\n\t\t\trole,\n\t\t\tname,\n\t\t}\n\t': AllAuthorsQueryResult;
    '*[_type == "category"].slug.current': CategorySlugsQueryResult;
  }
}
